#### Importing Libraries

In [1]:
import numpy as np # Numpy we are using for numerical calculation in python 
import pandas as pd # pandas we are using for data frame and analysis in python 
import matplotlib.pyplot as plt #matplotlib we are using it for ploting and visuilazing the data in python
import seaborn as sns #seaborn we are using it for ploting and visuilazing the data in python
import statsmodels.api as sm
%matplotlib inline 
sns.set(style="whitegrid")
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

#### Importing the Housing data

In [2]:
csv_housing_data = pd.read_csv(r"C:\Learning\Data\housing.data")

#### Displaying Top 10 rows of Housing Data

In [3]:
csv_housing_data.head(10)

   0.00632  18.00   2.310  0  0.5380  6.5750  65.20  4.0900   1  296.0  15.30 396.90   4.98  24.00
0   0.02731   0.00   7.070  0  0.4690  6.4210  78...
1   0.02729   0.00   7.070  0  0.4690  7.1850  61...
2   0.03237   0.00   2.180  0  0.4580  6.9980  45...
3   0.06905   0.00   2.180  0  0.4580  7.1470  54...
4   0.02985   0.00   2.180  0  0.4580  6.4300  58...
5   0.08829  12.50   7.870  0  0.5240  6.0120  66...
6   0.14455  12.50   7.870  0  0.5240  6.1720  96...
7   0.21124  12.50   7.870  0  0.5240  5.6310 100...
8   0.17004  12.50   7.870  0  0.5240  6.0040  85...
9   0.22489  12.50   7.870  0  0.5240  6.3770  94...

#### Importing the Housing data CSV by considering that there are no headers in the CSV and also considering column separator is whitespace

In [4]:
housing_data = pd.read_csv(r"C:\Learning\Data\housing.data",header=None,delim_whitespace=True)

#### Displaying Top 10 rows of Housing data without Column Headers

In [5]:
housing_data.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
5,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222.0,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,0,0.524,6.012,66.6,5.5605,5,311.0,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0,0.524,6.172,96.1,5.9505,5,311.0,15.2,396.90,19.15,27.1
8,0.21124,12.5,7.87,0,0.524,5.631,100.0,6.0821,5,311.0,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0,0.524,6.004,85.9,6.5921,5,311.0,15.2,386.71,17.10,18.9

#### Adding Column names to the data frame

In [6]:
housing_data.columns = ["CRIM","ZN","INDUS","CHAS","NOX","RM","AGE","DIS","RAD","TAX","PTRATIO","B","LSTAT","MEDV"]

#### Displaying Top 5 rows with Header

In [7]:
housing_data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

#### Declaring list of input variables and target/dependant variable

In [8]:
x_columns = ["CRIM","ZN","INDUS","CHAS","NOX","RM","AGE","DIS","RAD","TAX","PTRATIO","B","LSTAT"]
pdx = housing_data[x_columns]
pdy = housing_data["MEDV"]

#### Split the training data and test data by considering 70:30 ratio

In [9]:
x_train, x_test,y_train,y_test = train_test_split(pdx,pdy,train_size=70/100,random_state = 70)

#### Intercepting the data for Ordinary Least Square Model

In [10]:
x_train_cons = sm.add_constant (x_train)
x_test_cons = sm.add_constant (x_test)
full_mod = sm.OLS(y_train,x_train_cons)

#### Fitting the model and Printing the Result

In [11]:
regression_full = full_mod.fit()
print(regression_full.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   MEDV   R-squared:                       0.738
Model:                            OLS   Adj. R-squared:                  0.728
Method:                 Least Squares   F-statistic:                     73.82
Date:                Mon, 12 Apr 2021   Prob (F-statistic):           1.37e-90
Time:                        07:48:29   Log-Likelihood:                -1038.4
No. Observations:                 354   AIC:                             2105.
Df Residuals:                     340   BIC:                             2159.
Df Model:                          13
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         38.5890      5.969      6.464      0.000      26.847      50.331
CRIM          -0.1477      0.039     -3.831      0.000      -0.224      -0.072
ZN             0.0470      0.017      2.804      0.005       0.014       0.080
INDUS         -0.0528      0.070     -0.754      0.451      -0.191       0.085
CHAS           2.7872      1.038      2.685      0.008       0.745       4.829
NOX          -19.6572      4.603     -4.271      0.000     -28.711     -10.604
RM             3.3784      0.495      6.819      0.000       2.404       4.353
AGE            0.0068      0.015      0.441      0.659      -0.024       0.037
DIS           -1.7320      0.239     -7.239      0.000      -2.203      -1.261
RAD            0.3132      0.077      4.082      0.000       0.162       0.464
TAX           -0.0112      0.004     -2.602      0.010      -0.020      -0.003
PTRATIO       -0.8410      0.152     -5.525      0.000      -1.140      -0.542
B              0.0114      0.003      3.651      0.000       0.005       0.018
LSTAT         -0.5452      0.058     -9.436      0.000      -0.659      -0.432
==============================================================================
Omnibus:                      116.762   Durbin-Watson:                   2.008
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              463.006
Skew:                           1.393   Prob(JB):                    2.88e-101
Kurtosis:                       7.861   Cond. No.                     1.53e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.53e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [12]:
print("Variance Inflation Factor")
cnames = x_train.columns
for i in (np.arange(0,len(cnames))):
    xvars = list(cnames)
    yvar = xvars.pop(i)
    mod = sm.OLS(x_train[yvar],sm.add_constant(x_train_cons[xvars]))
    res = mod.fit()
    vif = 1/(1-res.rsquared)
    print(yvar,round(vif,3))

Variance Inflation Factor
CRIM 1.772
ZN 2.475
INDUS 3.839
CHAS 1.121
NOX 4.592
RM 1.834
AGE 3.162
DIS 4.207
RAD 7.365
TAX 8.645
PTRATIO 1.739
B 1.303
LSTAT 2.769

#### In the above iteration R-Square Value is 0.738 and Adjacent R-Square Value is 0.728. 
#### Probability value is high for the columns AGE - 0.659 & INDUS - 0.451
#### Going to Run one more iteration by removing the independant variable AGE

In [13]:
x_columns = ["CRIM","ZN","INDUS","CHAS","NOX","RM","DIS","RAD","TAX","PTRATIO","B","LSTAT"]
pdx = housing_data[x_columns]
pdy = housing_data["MEDV"]

x_train, x_test,y_train,y_test = train_test_split(pdx,pdy,train_size=70/100,random_state = 70)

x_train_cons = sm.add_constant (x_train)
x_test_cons = sm.add_constant (x_test)
full_mod = sm.OLS(y_train,x_train_cons)

regression_full = full_mod.fit()
print("Iteration-2", regression_full.summary())

print("Variance Inflation Factor")
cnames = x_train.columns
for i in (np.arange(0,len(cnames))):
    xvars = list(cnames)
    yvar = xvars.pop(i)
    mod = sm.OLS(x_train[yvar],sm.add_constant(x_train_cons[xvars]))
    res = mod.fit()
    vif = 1/(1-res.rsquared)
    print(yvar,round(vif,3))

Iteration-2                             OLS Regression Results
==============================================================================
Dep. Variable:                   MEDV   R-squared:                       0.738
Model:                            OLS   Adj. R-squared:                  0.729
Method:                 Least Squares   F-statistic:                     80.14
Date:                Mon, 12 Apr 2021   Prob (F-statistic):           1.65e-91
Time:                        07:48:29   Log-Likelihood:                -1038.5
No. Observations:                 354   AIC:                             2103.
Df Residuals:                     341   BIC:                             2153.
Df Model:                          12
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         38.3247      5.932      6.460      0.000      26.656      49.993
CRIM          -0.1477      0.039     -3.835      0.000      -0.223      -0.072
ZN             0.0463      0.017      2.777      0.006       0.014       0.079
INDUS         -0.0513      0.070     -0.734      0.464      -0.189       0.086
CHAS           2.8001      1.037      2.701      0.007       0.761       4.839
NOX          -19.1109      4.428     -4.316      0.000     -27.820     -10.401
RM             3.4279      0.482      7.112      0.000       2.480       4.376
DIS           -1.7591      0.231     -7.616      0.000      -2.213      -1.305
RAD            0.3110      0.076      4.067      0.000       0.161       0.461
TAX           -0.0112      0.004     -2.597      0.010      -0.020      -0.003
PTRATIO       -0.8381      0.152     -5.518      0.000      -1.137      -0.539
B              0.0115      0.003      3.704      0.000       0.005       0.018
LSTAT         -0.5362      0.054     -9.938      0.000      -0.642      -0.430
==============================================================================
Omnibus:                      118.824   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              483.322
Skew:                           1.410   Prob(JB):                    1.12e-105
Kurtosis:                       7.981   Cond. No.                     1.50e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.5e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
Variance Inflation Factor
CRIM 1.772
ZN 2.45
INDUS 3.83
CHAS 1.12
NOX 4.259
RM 1.74
DIS 3.93
RAD 7.334
TAX 8.641
PTRATIO 1.736
B 1.294
LSTAT 2.42

#### In the 2nd Iteration, R-Square Value is 0.738 and Adjacent R-Square Value is 0.729. There is not that much difference.
#### Executing one more iteration by removing INDUS variable.

In [14]:
x_columns = ["CRIM","ZN","CHAS","NOX","RM","DIS","RAD","TAX","PTRATIO","B","LSTAT"]

pdx = housing_data[x_columns]
pdy = housing_data["MEDV"]

x_train, x_test,y_train,y_test = train_test_split(pdx,pdy,train_size=70/100,random_state = 70)

x_train_cons = sm.add_constant (x_train)
x_test_cons = sm.add_constant (x_test)
full_mod = sm.OLS(y_train,x_train_cons)

regression_full = full_mod.fit()
print("Iteration-3", regression_full.summary())

print("Variance Inflation Factor")
cnames = x_train.columns
for i in (np.arange(0,len(cnames))):
    xvars = list(cnames)
    yvar = xvars.pop(i)
    mod = sm.OLS(x_train[yvar],sm.add_constant(x_train_cons[xvars]))
    res = mod.fit()
    vif = 1/(1-res.rsquared)
    print(yvar,round(vif,3))

Iteration-3                             OLS Regression Results
==============================================================================
Dep. Variable:                   MEDV   R-squared:                       0.738
Model:                            OLS   Adj. R-squared:                  0.729
Method:                 Least Squares   F-statistic:                     87.50
Date:                Mon, 12 Apr 2021   Prob (F-statistic):           2.24e-92
Time:                        07:48:30   Log-Likelihood:                -1038.8
No. Observations:                 354   AIC:                             2102.
Df Residuals:                     342   BIC:                             2148.
Df Model:                          11
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         38.4584      5.925      6.490      0.000      26.803      50.113
CRIM          -0.1471      0.038     -3.824      0.000      -0.223      -0.071
ZN             0.0476      0.017      2.878      0.004       0.015       0.080
CHAS           2.7338      1.032      2.649      0.008       0.704       4.763
NOX          -19.9474      4.276     -4.665      0.000     -28.358     -11.537
RM             3.4705      0.478      7.258      0.000       2.530       4.411
DIS           -1.7245      0.226     -7.632      0.000      -2.169      -1.280
RAD            0.3270      0.073      4.464      0.000       0.183       0.471
TAX           -0.0126      0.004     -3.252      0.001      -0.020      -0.005
PTRATIO       -0.8514      0.151     -5.650      0.000      -1.148      -0.555
B              0.0116      0.003      3.748      0.000       0.006       0.018
LSTAT         -0.5386      0.054    -10.009      0.000      -0.644      -0.433
==============================================================================
Omnibus:                      118.437   Durbin-Watson:                   2.006
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              479.784
Skew:                           1.407   Prob(JB):                    6.55e-105
Kurtosis:                       7.961   Cond. No.                     1.49e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.49e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
Variance Inflation Factor
CRIM 1.771
ZN 2.421
CHAS 1.111
NOX 3.977
RM 1.715
DIS 3.766
RAD 6.737
TAX 6.973
PTRATIO 1.711
B 1.291
LSTAT 2.411

#### In the 3rd iteration too, there is not that much difference. R-Square Value is 0.738 and Adjacent R-Square Value is 0.729

In [15]:
y_pred = regression_full.predict(x_test_cons)
y_pred_df = pd.DataFrame(y_pred)
y_pred_df.columns= ['y_pred']

pred_data = pd.DataFrame(y_pred_df['y_pred'])
y_test_cons = pd.DataFrame(y_test)
y_test_cons.reset_index(inplace=True)
pred_data['y_test'] = pd.DataFrame(y_test_cons['MEDV'])

In [16]:
rsqd = r2_score(y_test_cons['MEDV'].tolist(),y_pred_df['y_pred'].tolist())
print('Test R-Squared Value:',round(rsqd,4))

Test R-Squared Value: 0.7356